name: Run Fuzzer

on:
  push:
    branches:
      - main

jobs:
  run-fuzzer:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make executable
        run: chmod +x html_parser_linux_x86_64

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Compile the Fuzzer
      - name: Compile Fuzzer
        run: javac Fuzzer.java

      # Run the Fuzzer
      - name: Run Fuzzer
        run: java Fuzzer html_parser_linux_x86_64
